blog/urls.py
from django.urls import path
from .views import (
    UserPostListView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
urlpatterns = [
    #path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('about/', views.about, name='blog-about'),

]

ecommerce_site/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from ecommerce import views as ecommerce_views
from products import views as products_views

urlpatterns = [
    path('', include('products.urls')),
    path('', include('ecommerce.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (
    Product_create_view,
    product_detail_view,
    product_delete_view,
    product_list_view,
    product_update_view,
    product_category_view,
    Purchase_detail_view,
    Purchase_create_view,
    Purchase_list_view,

)

app_name = 'products'
urlpatterns = [
    path('products/', product_list_view, name='product-list'),
    path('products/create/', Product_create_view.as_view(), name='product-create'),
    path('products/<int:id>/', product_detail_view, name='product-detail'),
    path('products/<int:id>/update/', product_update_view, name='product-update'),
    path('products/<int:id>/delete/', product_delete_view, name='product-delete'),
    path('products/<str:category>/', product_category_view, name='product-category'),
    path('purchases/<int:pk>/', Purchase_detail_view.as_view(), name='purchase-detail'),
    path('purchases/<str:username>', Purchase_list_view.as_view(), name='purchases'),
    path('products/<int:pk>/purchase/', Purchase_create_view.as_view(), name='purchase-create'),

]

products/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User



# Create your models here.
class Product(models.Model):
    CATEGORY_CHOICES = (
    ('services', 'SERVICES'),
    ('garden', 'GARDEN'),
    ('electronic', 'ELECTRONIC'),
    ('clothes', 'CLOTHES'),
    ('hobbies', 'HOBBIES'),
    )
    title       = models.CharField(max_length=120) # max_length = required
    description = models.TextField(blank=True, null=True)
    price       = models.DecimalField(decimal_places=2, max_digits=10000)
    featured    = models.BooleanField(default=False) # null=True, default=True
    author      = models.ForeignKey(User, on_delete=models.CASCADE, default="1")
    date_posted = models.DateTimeField(default=timezone.now)
    category    = models.CharField(max_length=120, choices=CATEGORY_CHOICES, default='services')

    def get_absolute_url(self):
        return reverse('products:product-detail', kwargs={'id': self.id})



    # Para que se vea el título del post al imprimirlo en el shell
    def __str__(self):
        return self.title


# Create your models here.
class Purchase(models.Model):
    PAYMENT_CHOICES = (
    ('cash', 'CASH'),
    ('debit card', 'DEBIT CARD'),
    ('credit card', 'CREDIT CARD')
    )
    product        = models.ForeignKey(Product, on_delete=models.CASCADE)
    user           = models.ForeignKey(User, on_delete=models.CASCADE)
    amount         = models.IntegerField(default=1)
    date_purchased = models.DateTimeField(default=timezone.now)
    pay_mode       = models.CharField(max_length=30, choices=PAYMENT_CHOICES, default='cash')
    state          = models.CharField(max_length=30, default='closed')

    def get_absolute_url(self):
        return reverse('products:purchase-detail', kwargs={'pk': self.pk})



    # Para que se vea el título del post al imprimirlo en el shell
    def __str__(self):
        return self.product.title

products/forms.py
from django import forms
from .models import Purchase


class PurchaseModelForm(forms.ModelForm):
    class Meta:
        model = Purchase
        exclude =(
            'user',
            'product',
        )

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Purchase
from django.contrib.auth.models import User
from django.views.decorators.csrf import ensure_csrf_cookie
from .forms import PurchaseModelForm
from django.urls import reverse

from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
 )
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)

class Product_create_view(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['title', 'description', 'price', 'category']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def product_update_view(request, id=id):
    obj = get_object_or_404(Product, id=id)
    form = ProductForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, "products/product_create.html", context)


def product_list_view(request):
    queryset = Product.objects.all() # list of objects
    context = {
        "object_list": queryset
    }
    return render(request, "products/product_list.html", context)


def product_category_view(request, category):
    queryset = Product.objects.filter(category=category) # list of objects
    CATEGORY_CHOICES = Product.CATEGORY_CHOICES
    context = {
        "products": queryset,
        "CATEGORY_CHOICES": CATEGORY_CHOICES,
        "selected_category": category
    }

    return render(request, "products/product_category_view.html", context)

def product_detail_view(request, id):
    obj = get_object_or_404(Product, id=id)
    context = {
        "object": obj
    }
    return render(request, "products/product_detail.html", context)


def product_delete_view(request, id):
    obj = get_object_or_404(Product, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect('../../')
    context = {
        "object": obj
    }
    return render(request, "products/product_delete.html", context)


class Purchase_list_view(ListView):
    model = Purchase
    template_name = 'products/purchase_list.html'
    context_object_name = 'purchases'
    ordering = ['-date_purchased']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        print(user)
        return Purchase.objects.filter(user=user).order_by('-date_purchased')


class Purchase_detail_view(DetailView):
    model = Purchase

class Purchase_create_view(LoginRequiredMixin, CreateView):
    model = Purchase
    form = PurchaseModelForm
    template_name= 'products/purchase_form.html'
    fields = ['pay_mode', 'amount']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.product = Product.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('products:purchases',kwargs={'username': self.request.user} )

products/templates/products/product_browser.html
{% extends "ecommerce/base.html" %}
{% block content %}
<div class="card-deck">
  {% for product in products %}
  <div class="card">
    <img class="card-img-top" src="{{ product.author.profile.image.url }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">
        <a class="article-title" href="{% url 'products:product-detail' product.id %}">{{ product.title }}</a>
      </h5>
      <p class="card-text">{{ product.price }}</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">{{ product.date_posted|date:"F d, Y" }}</small>
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}

products/templates/products/product_category_view.html
{% extends "ecommerce/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h2>Categories</h2>
      <ul>
        {% for val, name in CATEGORY_CHOICES %}
          {% if val == selected_category %}
            <li style="color:blue;">{{ val }}</li>
            {% else %}
            <li>{{ val }}</li>
            {% endif %}
        {% endfor %}
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="card-deck">
        {% for product in products %}
        <a class="card" href="{% url 'products:product-detail' product.id %}">
          <img class="card-img-top" src="{{ product.author.profile.image.url }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">
              {{ product.title }}
            </h5>
            <p class="card-text">{{ product.price }}</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">{{ product.date_posted|date:"F d, Y" }}</small>
          </div>
        </a>
        {% endfor %}

      </div>
    </div>
  </div>
</div>

{% endblock %}

products/templates/products/product_detail.html
{% extends 'ecommerce/base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.description }}</p>
<a href="{% url 'products:purchase-create' pk=object.pk %}" class="btn btn-success" >Buy</a>
{% endblock %}

products/templates/products/product_form.html
{% extends 'ecommerce/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method='POST'>
  {% csrf_token %}

  <div class="form-group">
    <label for="exampleFormControlInput1">  Product name </label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Producto" value="{{current_name}}">
  </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">  Product description </label>
    <input type="text" class="form-control" id="description" name="description" placeholder="Description" value="{{current_description}}">
  </div>
  <div class="form-group">
    <label for="exampleFormControlInput1">  Price </label>
    <input type="text" class="form-control" id="price" name="price" placeholder="Price" value="{{current_price}}">
  </div>

  <div class="form-group">
    <label for="category">Category</label>
    <select class="form-control" id="category" name="category" >
      {% for val, name in form.fields.category.choices %}
      <option value="{{ val }}">{{ name }}</option>
      {% endfor %}
    </select>
  </div>


  <button type="submit" value="save" class="btn btn-primary">Submit</button>

</form>


<p>{{ object.description }}</p>
{% endblock %}

products/templates/products/product_list.html
{% extends 'ecommerce/base.html' %}

{% block content %}



{% for instance in object_list %}
     <p>{{ instance.id }} - <a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></p>
{% endfor %}


{% endblock %}

products/templates/products/purchase_detail.html
{% extends 'ecommerce/base.html' %}

{% block content %}
<h1>{{ object.product.title}}</h1>
<h1>{{ object.state}}</h1>
<p>{{ object.pay_mode }}</p>
{% endblock %}

products/templates/products/purchase_form.html
{% extends 'ecommerce/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form action="" method="POST">
  {% csrf_token %}
  <p>hola {{user}}</p>

  
  <div class="form-group">
    <label for="exampleFormControlInput1"> amount </label>
    <input type="text" class="form-control" id="amount" name="amount" placeholder="amount" value="{{current_amount}}">
  </div>



  <div class="form-group">
    <label for="pay_mode">Pay mode</label>
    <select class="form-control" id="pay_mode" name="pay_mode">
      {% for val, name in form.fields.pay_mode.choices %}
      <option value="{{ val }}">{{ name }}</option>
      {% endfor %}
    </select>
  </div>


  <button type="submit" value="save" class="btn btn-primary">Buy</button>

</form>


{% endblock %}

products/templates/products/purchase_list.html
{% extends 'ecommerce/base.html' %}
{% block content %}

<h3>My purchases</h3>
{% for instance in object_list %}
     <p>{{ forloop.counter }} - <a href='{{ instance.get_absolute_url }}'>{{ instance.product.title }}</a></p>
{% endfor %}


{% endblock %}